config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"

  devise_for :users

  resources :likes, only: [:create, :destroy]
  resources :hates, only: [:create, :destroy]
  resources :movies, only: [:new, :create, :show, :index]

  resources :users do
    resources :movies
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hate.rb
class Hate < Vote
  after_save :destroy_movie_like
  belongs_to :movie, :counter_cache => true

  # Destroys any like of same user to same movie.
  # a user cannot both like and hate a movie the same time.
  #
  def destroy_movie_like
    Like.find_by(user: user, movie: movie).try(:destroy)
  end
end

app/models/like.rb
class Like < Vote
  after_save :destroy_movie_hate
  belongs_to :movie, :counter_cache => true

  def destroy_movie_hate
    Hate.find_by(user: user, movie: movie).try(:destroy)
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :likes
  has_many :hates
  belongs_to :user
  has_many :liking_users, through: :likes, source: :user
  has_many :hating_users, through: :hates, source: :user

  scope :ordered_by_likes,  -> { order(likes_count: :desc, hates_count: :asc) }
  scope :ordered_by_hates,  -> { order(hates_count: :desc, likes_count: :asc) }
  scope :ordered_by_date,   -> { order(created_at: :desc) }
  scope :user_scoped,       -> (user_id) { where(user_id: user_id) if user_id.present? }

  SORT_OPTIONS = ['likes', 'hates', 'date']

  def has_votes?
    !(likes_count + hates_count).zero?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
  has_many :likes
  has_many :hates
  has_many :liked_movies, through: :likes, source: :movie
  has_many :hated_movies, through: :hates, source: :movie

  validates :first_name, presence: true
  validates :last_name, presence: true

  def nickname
    @nickname ||= [first_name, last_name].join(" ")
  end

  def get_liked_movies_ids
    @liked_movies_ids ||= liked_movies.map(&:id)
  end

  def get_hated_movies_ids
    @hated_movies_ids ||= hated_movies.map(&:id)
  end

  def likes_movie?(movie)
    get_liked_movies_ids.include?(movie.id)
  end

  def hates_movie?(movie)
    get_hated_movies_ids.include?(movie.id)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/hates_controller.rb
class HatesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_hate, only: [:destroy]

  # POST /hates
  # POST /hates.json
  def create
    # Stops someone who wants to vote for his movies.
    redirect_to movies_path, alert: 'Voting for same user is not allowed' and return if current_user.movie_ids.include?(hate_params[:movie_id].to_i)

    @hate = Hate.find_or_initialize_by(movie_id: hate_params[:movie_id], user_id: current_user.id)

    @hate.attributes.merge(hate_params)

    respond_to do |format|
      if @hate.save
        format.html { redirect_to movies_path, notice: 'Hate was successfully created.' }
        format.json { render :show, status: :created, location: @hate }
      else
        format.html { render :new }
        format.json { render json: @hate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hates/1
  # DELETE /hates/1.json
  def destroy
    respond_to do |format|
      if @hate && @hate.destroy
        format.html { redirect_to movies_url, notice: 'Hate was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to movies_url, notice: 'Hate could not be destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hate
      @hate = current_user.hates.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hate_params
      params.require(:hate).permit(:movie_id)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_like, only: [:destroy]

  # POST /likes
  # POST /likes.json
  def create
    # Stops someone who wants to vote for his movies.
    redirect_to movies_path, alert: 'Voting for same user is not allowed' and return if current_user.movie_ids.include?(like_params[:movie_id].to_i)

    @like = Like.find_or_initialize_by(movie_id: like_params[:movie_id], user_id: current_user.id)

    @like.attributes.merge(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to movies_path, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    respond_to do |format|
      if @like && @like.destroy
        format.html { redirect_to movies_url, notice: 'Like was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to movies_url, alert: 'Like could not be destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = current_user.likes.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:movie_id)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :create]
  before_action :set_movie, only: [:show]

  # GET /movies
  # GET /movies.json
  def index
    sort_scope  = "ordered_by_" << (Movie::SORT_OPTIONS.include?(params[:sort]) ? params[:sort] : "likes")
    user_scope  = params[:user_id]

    @movies     = Movie.user_scoped(user_scope).send(sort_scope)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hates_helper.rb
module HatesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Returns user's first_name and last_name or 'You'.
  def get_user_nickname(movie)
    return '' unless movie.class == Movie
    movie.user == current_user ? 'You' : movie.user.nickname
  end
end

app/views/application/_header.html.erb
<div class="header">
  <div class="col">
    <h1 class="logo"><%= link_to "MovieRama", root_path %></h1>
  </div>
  <div class="col">
    <% if user_signed_in?%>
      Welcome back <%= link_to current_user.nickname, destroy_user_session_path, method: :delete %>
    <% else %>
      <span><%= link_to "Log_in", new_user_session_path %></span> or <span class="signup"><%= button_to "Sign up", new_user_registration_path, method: "get" %></span>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieRama</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render "header" %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field full-width">
    <%= form.label :title %>
    <%= form.text_field :title, id: :movie_title %>
  </div>

  <div class="field full-width">
    <%= form.label :description %>
    <%= form.text_area :description, id: :movie_description, cols: 60, rows: 12 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_unvotes.html.erb
<% if current_user.likes_movie?(movie) %>
  <div class="col align-right">
    You like this movie
    |
    <%= link_to 'Unlike', like_path(movie.likes.find_by(user: current_user)), method: 'delete' %>
  </div>
<% elsif current_user.hates_movie?(movie) %>
  <div class="col align-right">
    You hate this movie
    |
    <%= link_to 'Unhate', hate_path(movie.hates.find_by(user: current_user)), method: 'delete' %>
  </div>
<% end %>

app/views/movies/_votes.html.erb
<% if user_signed_in? && movie.user != current_user %>
  <% if movie.has_votes? %>
    <div class="col">
      <% if current_user.likes_movie?(movie) %>
        <%= t('likes', count: movie.likes_count) %>
      <% else %>
        <%= link_to "#{t('likes', count: movie.likes_count)}", likes_path(like: { movie_id: movie }), method: 'post' %>
      <% end %>
      |
      <% if current_user.hates_movie?(movie) %>
        <%= t('hates', count: movie.hates_count) %>
      <% else %>
        <%= link_to "#{t('hates', count: movie.hates_count)}", hates_path(hate: { movie_id: movie }), method: 'post' %>
      <% end %>
    </div>
  <% else %>
    <div>
      <span>Be the first to vote for this movie: <%= link_to 'Like', likes_path(like: { movie_id: movie }), method: 'post'%></span>
      |
      <span><%=link_to 'Hate', hates_path(hate: { movie_id: movie }), method: 'post'%></span>
    </div>
  <% end %>
<% else %>
  <%= t('likes', count: movie.likes_count) %> | <%= t('hates', count: movie.hates_count) %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<div class="toolbox">
Sort by:
<% Movie::SORT_OPTIONS.each_with_index do |sort_option, index|%>
  <%= raw params[:sort] == sort_option ? sort_option.capitalize : "#{link_to sort_option.capitalize, url_for(sort: sort_option)}" %>
  <%= "|" if (index + 1) < Movie::SORT_OPTIONS.count %>
<% end %>
</div>

<div class="main inline-block">
  <% @movies.includes(:user).each do |movie| %>
    <div class="movie">
      <h2><%= movie.title%></h2>
      <p> Posted by <%= link_to get_user_nickname(movie), user_movies_path(movie.user) %> <%= time_ago_in_words(movie.created_at) %> ago</p>
      <p><%= movie.description %></p>
      <%= render partial: "votes", locals: { movie: movie } %>
      <%= render partial: "unvotes", locals: { movie: movie } if user_signed_in? %>
    </div>
  <% end %>
</div>

<div class="aside inline-block">
  <%= button_to 'New Movie', new_movie_path, method: "get", class: "button green" if user_signed_in? %>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= time_ago_in_words(@movie.created_at) %>
</p>

<p>
  <strong>User:</strong>
  <%= @movie.user.nickname %>
</p>

<%= link_to 'Back', movies_path %>